name: my_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - web/index.html
    - web/index-tr.html
    - web/app.js
    - web/own.js
    - web/particles.js
    - web/particles.json
    - web/style.css
    - web/popup.css

dev_dependencies:
  flutter_test:
    sdk: flutter
